// Code generated by mdatagen. DO NOT EDIT.

package telemetryapireceiver

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/component/componenttest"
)

var typ = component.MustNewType("telemetryapi")

func TestComponentFactoryType(t *testing.T) {
	require.Equal(t, typ, NewFactory("extensionID").Type())
}

func TestComponentConfigStruct(t *testing.T) {
	require.NoError(t, componenttest.CheckConfigStruct(NewFactory("extensionID").CreateDefaultConfig()))
}
